colcon_core/task/__init__.py

See https://github.com/gforcada/flake8-builtins/blob/1.3.0/CHANGES.rst#130-2018-04-13

update noqa rule to match latest flake8-builtins release

---

appveyor.yml

test with Python 3.6 on Windows

---

colcon_core/event/command.py
colcon_core/task/__init__.py
test/spell_check.words
test/test_event_handler_log_command.py

This should be helpful in debugging the return code of each invoked command.
~~Before this should be merged the test needs to be updated to cover the new event class.~~ I updated the test to cover the new event class.

add CommandEnded to log return code of each invoked command

---

colcon_core/task/python/test/pytest.py

Connect to colcon/colcon-cmake#6.

update help for --pytest-args

---

colcon_core/event/test.py
colcon_core/event_handler/console_start_end.py
colcon_core/task/python/test/pytest.py
colcon_core/verb/test.py

This will allow to react to failed tests. E.g. as also part of this patch mention the test failures as part of the "Finished <<< {pkgname}" message.

add test failure event

---

colcon_core/shell/template/package.sh.em

use zsh_to_array when available

---

colcon_core/logging.py

For additional context in the log.

add relative time to logger_all.log

---

colcon_core/environment/pythonpath.py

Just getting this out of my working copy. Simply reducing the scope of the variable where actually needed.

reduce scope of variable

---

colcon_core/shell/template/package.sh.em
colcon_core/subprocess.py
colcon_core/task/python/test/pytest.py
test/test_event_command.py
test/test_shell.py

Fixes #65 on Linux and Windows.

fix handling of paths with spaces

---

test/test_command.py

avoid creating log directory in package directory during testing

---

colcon_core/environment/__init__.py
colcon_core/location.py
colcon_core/shell/template/prefix_util.py
test/test_shell_template_prefix_util.py

Refactoring before using the same information for #76.

refactor package index path into common function

---

colcon_core/shell/template/prefix.bat.em
colcon_core/shell/template/prefix.sh.em

FIxes https://github.com/colcon/colcon-core/issues/85
Opening for visibility needs some testing still

improve check and fallback behavior for python executable

---

colcon_core/executor/__init__.py

Used by colcon/colcon-output#12.

expose Job task_context

---

colcon_core/task/__init__.py
colcon_core/verb/build.py
colcon_core/verb/test.py
test/test_task.py

support task entry point groups outside of the core

---

colcon_core/command.py

Only lazily add the verb arguments is mostly done to improve the completion performance (see colcon/colcon-argcomplete#10 for measuring it).
This needs the following extensions to be updated:
* colcon/colcon-argcomplete#11
* colcon/colcon-defaults#8
* colcon/colcon-mixin#3

only add verb args for the requested verb

---

colcon_core/dependency_descriptor.py
colcon_core/package_descriptor.py
test/spell_check.words
test/test_dependency_descriptor.py

add descriptor for package dependencies

---

colcon_core/executor/__init__.py
colcon_core/verb/test.py

add --return-code-on-test-failure to test verb

---

colcon_core/shell/template/prefix.sh.em

support bootstrapping with zsh

---

colcon_core/argument_parser/__init__.py
colcon_core/command.py

Follow up of colcon/colcon-core#143. When invoking `colcon` with invalid arguments (e.g. `colcon asdf`) the usage was printed also multiple times.

fix multiple usage output on invalid arguments

---

setup.cfg
test/spell_check.words
test/test_spell_check.py

Relying on the new API introduced in the latest release reduces the custom logic quite a bit.

use scspell 2.2

---

colcon_core/environment/__init__.py
colcon_core/shell/template/hook_prepend_value.bat.em
colcon_core/shell/template/hook_prepend_value.sh.em

Enabling colcon/colcon-ros#48.

expose create_environment_scripts_only() and allow absolute prepended values

---

colcon_core/task/python/build.py

Fixes ament/ament_cmake#152.
E.g. the environment variable `PYTHONPATH` contains already some paths - e.g. `/tmp` - and a package `foo` is being installed in `develop` mode. The resulting `PYTHONPATH` is `<install>/foo/<python-lib>:/tmp` which looks correct.
Though at runtime the `sys.path` is being extended when the `easy-install.pth` file in `<install>/foo/<python-lib>` is found and `<build>/foo` is being added - but *after* all paths listed in the `PYTHONPATH`. That implies that the resolution order changes by considering `/tmp` before `<build>/foo`.
This is in particular a problem if the package `foo` is supposed to be an *overlay* of the same package already present in a directory already mentioned in `PYTHONPATH`. Due to the changed order `foo` would be used from the underlay rather …

fix the order of prepended PYTHONPATH in develop mode if other paths are set in PYTHONPATH

---

colcon_core/event_handler/__init__.py

accept default event handler values

---

colcon_core/prefix_path/__init__.py
test/test_prefix_path.py

Addresses part of colcon/colcon-ros#58.

avoid duplicate prefix paths

---

colcon/__main__.py
colcon_core/command.py
test/test_command.py

add colcon __main__ module so user can 'python -m colcon'

---

colcon_core/package_identification/python.py

As reported in https://github.com/colcon/colcon-core/pull/184#discussion_r279201215

fix string formatting of warning message

---

colcon_core/executor/sequential.py

Fixes regression of #187.
An explicit loop is require on macOS and Windows.

pass loop explicitly

---

colcon_core/event_handler/console_start_end.py
colcon_core/event_reactor.py

Making the duration values robust to clock jumps.

use monotonic clock for duration

---

colcon_core/package_identification/python.py

Related to colcon/colcon-ros#57.

add version to package metadata

---

colcon_core/event_handler/console_start_end.py

Fix linter warning introduced in #201.

fix linter warning about line length

---

colcon_core/shell/template/prefix_util.py.em

Follow up of #209. Related to ros2/ros2#764.
This requires the following two PRs since the ament hooks can't expect any external shell functions to be defined:
* ros2/rosidl_typesupport_connext#35
* ros2/rosidl_typesupport_opensplice#40

fix environment calculation to also use .dsv files the ament hooks

---

colcon_core/shell/bat.py
colcon_core/shell/sh.py
colcon_core/shell/template/hook_set_value.bat.em
colcon_core/shell/template/hook_set_value.sh.em

Needed for colcon/colcon-ros#76.

implement create_hook_set_value for sh and bash

---

colcon_core/subprocess.py

Detected using this new feature: #232.

close file handle after use

---

colcon_core/command.py
colcon_core/location.py

Support setting `COLCON_LOG_PATH` / `--log-base` to `os.devnull` to disable logging.

support disabling logging

---

colcon_core/shell/dsv.py
colcon_core/shell/template/hook_set_value.dsv.em
colcon_core/shell/template/prefix_util.py.em

Follow up of #209 adding a new type: `set`.

add type 'set' for dsv files

---

colcon_core/shell/template/prefix_util.py.em

Useful for ros/ros_environment#19.

add dsv type set-if-unset

---

colcon_core/package_identification/__init__.py

Refactor the always copied descriptors which are supposed to be updated by an extension to reuse the copied descriptor in the next cycle if it hasn't been changed. That avoids a `deepcopy` of the descriptor in the majority of the cases.
For an example ROS 2 workspace with 268 pkgs the time to list goes down by roughly 10% (from 1.7s to 1.55s).

avoid repeated deepcopy of descriptors during identification

---

colcon_core/event_reactor.py
colcon_core/executor/__init__.py
test/test_event_reactor.py
test/test_executor.py

Make EventReactor a context manager
Use Thread via composition instead of inheritance

More Pythonic EventReactor

---

colcon_core/command.py
test/test_flake8.py
test/test_logging.py

Follow up of #233 updating the documented default value and the test.

use warning instead of warn in default value

---

colcon_core/event/__init__.py

See https://github.com/colcon/colcon-core/blob/51541bd34ba56cb8064778d4447a238c61e11ea7/colcon_core/event_reactor.py#L18

fix reference in docblock

---

colcon_core/command.py

add comment with expanded env var name for searchability

---

colcon_core/subprocess.py

Follow up of #284 
As of Python 3.8 passing coroutines to `asyncio.wait` is deprecated. The patch ensures to convert all arguments into tasks (futures in earlier Python versions).

convert coroutines into tasks for Python 3.8

---

colcon_core/command.py

Needed for an updated version of colcon/colcon-package-information#28.

expose prog name used for argparse parser

---

test/test_package_discovery.py

https://travis-ci.org/colcon/colcon-core/jobs/642205616?utm_medium=notification&utm_source=github_status

fix flake8-comprehensions warnings

---

.travis.yml

Not sure what has changed in the last two days when the `bootstrap` test passed just fine on `master`.

install test_requires for bootstrap tests

---

.travis.yml

Follow up of #297.
Again a bit awkward since the CI passed on #297 but doesn't pass on #296 without the changes from this PR...

install all tests_require for bootstrap test

---

colcon_core/shell/__init__.py
colcon_core/shell/bat.py
colcon_core/shell/sh.py

Related to colcon/colcon-ros#95.

standardize behavior when passing an empty string

---

colcon_core/package_descriptor.py

Compute PackageDescriptor.realpath eagerly
reduces the runtime of get_packages from about 20s to 7s

Speed up colcon list

---

test/test_executor_sequential.py

fix missing function argument in Windows test

---

colcon_core/package_descriptor.py
test/test_package_descriptor.py

Chops time in half for `colcon list` on Windows! Hiya!

Make colcon list even fasterer

---

colcon_core/argument_parser/__init__.py
colcon_core/argument_parser/destination_collector.py
test/spell_check.words
test/test_destination_collector.py

Related to colcon/colcon-defaults#21.

add flag to query non-recursive parser argument destinations

---

colcon_core/command.py

Related to colcon/colcon-defaults#22.

support non-numeric log-level defaults

---

colcon_core/task/python/test/pytest.py
colcon_core/task/python/test/setuppy_test.py

Partially addresses colcon/colcon-cmake#70.

add note to help message that stdout might not be shown by default

---

colcon_core/event/job.py
colcon_core/executor/__init__.py
colcon_core/verb/build.py
test/test_executor.py

See colcon/colcon-cmake#69 how this new event is being used.

 add JobUnselected event to the build verb 

---

colcon_core/subprocess.py
colcon_core/task/__init__.py
colcon_core/task/python/build.py
colcon_core/task/python/test/pytest.py
colcon_core/task/python/test/setuppy_test.py

I assume rc stood for "return code", but it's a CompletedProcess object.
Also, don't check if check_call returns None. It never does.

rename rc -> completed

---

colcon_core/argument_default.py
test/test_argument_default.py

Follow up of #288 providing the inverse function.

add unwrap_default_value function

---

colcon_core/argument_parser/__init__.py
colcon_core/executor/__init__.py
colcon_core/task/__init__.py
pytest.ini
test/spell_check.words
test/test_dependency_descriptor.py
test/test_event_handler_console_start_end.py
test/test_location.py
test/test_package_descriptor.py
test/test_shell_template.py
test/test_verb.py

Add tests for a few lines / branches / functions not covered in these modules before.

increase code coverage: deepcopy dependency descriptor, log location, compare package descriptors, update_object

---

test/test_event_reactor.py

E.g. https://ci.appveyor.com/project/dirk-thomas/colcon-core/builds/32694401

relax timing race in event_reactor test

---

codecov.yml

Follow up of #346.
As e.g. seen on #350.

fix codecov patch threshold config

---

colcon_core/task/python/test/__init__.py

Described in colcon/colcon-ros#105.

fix --python-testing argument

---

colcon_core/location.py
colcon_core/task/python/build.py
test/spell_check.words
test/test_build_python.py

Just for shorter, more readable code.

use contextlib.suppress

---

colcon_core/subprocess.py

To avoid controversial terminology.

rename internal variable returned by pty.openpty

---

colcon_core/task/python/build.py

support renaming through package_dir

---

colcon_core/package_augmentation/python.py
colcon_core/package_identification/python.py
setup.cfg
test/test_package_identification_python.py

move Python dependencies and metadata extraction from identification to augmentation module

---

colcon_core/task/python/build.py

handle Python scripts in symlink install

---

colcon_core/command.py
colcon_core/location.py
test/test_location.py

reset global state in location module after command finished

---

colcon_core/task/python/build.py

support building Python packages using distutils

---

.travis.yml
appveyor.yml
colcon_core/task/python/build.py

Change import order to pass flake8-import-order, reenable in CI

---

colcon_core/package_augmentation/python.py
colcon_core/package_discovery/path.py
colcon_core/shell/bat.py
colcon_core/shell/dsv.py
colcon_core/shell/sh.py
test/test_plugin_system.py

Recent releases of flake8 plugins are causing CI to fail. This change addresses those issues.
For example: https://travis-ci.org/github/colcon/colcon-core/jobs/764586378

Appease the latest flake8 plugin releases

---

colcon_core/shell/__init__.py
colcon_core/shell/bat.py
colcon_core/shell/dsv.py
colcon_core/shell/sh.py
colcon_core/shell/template/hook_append_value.bat.em
colcon_core/shell/template/hook_append_value.dsv.em
colcon_core/shell/template/hook_append_value.sh.em
colcon_core/shell/template/prefix.bat.em
colcon_core/shell/template/prefix_util.py.em
test/test_shell.py
test/test_shell_bat.py
test/test_shell_sh.py

It looks like support for this flag was templated, but was never implemented. I'd like to use it in the same way we're currently using the prepending variant.

Implement create_hook_append_value

---

colcon_core/topological_order.py

This function is currently doing a few discrete things:
1. Decorating descriptors
2. Adding recursive dependencies
3. Ordering decorators
4. Ordering recursive dependencies on decorators
There are already dedicated functions for performing the first two tasks, so this change introduces a new topological_order_decorators function which includes only the novel parts of topological_order_packages and makes the original function call into the three functions that accomplish the same tasks.
After teasing the duplicated code apart, the actual topological ordering portion of the algorithm could be simplified and no longer required the temporary object for storing pre-decorated descriptors.
There isn't really any reason to deprecate the original function, but the improved code reuse results in …

Break apart topological_order_packages function

---

colcon_core/shell/template/prefix_util.py.em

Add support for comment lines in dsv files

---

setup.cfg

This is indeed a problem, but we need to be able to run tests until we're ready to make a fix.
I filed #552 to follow-up with a fix.

Suppress DeprecationWarning in pkg_resources

---

colcon_core/package_identification/python.py
colcon_core/plugin_system.py
colcon_core/task/python/test/pytest.py
debian/patches/setup.cfg.patch
setup.cfg
test/spell_check.words

Switch from pkg_resources to packaging for version comparison

---

stdeb.cfg

Add missing debian dependency on python3-packaging

---

colcon_core/extension_point.py
colcon_core/package_identification/python.py
colcon_core/plugin_system.py
colcon_core/task/python/test/pytest.py
debian/patches/setup.cfg.patch
setup.cfg
stdeb.cfg
test/spell_check.words
test/test_extension_point.py

Restore use of importlib.metadata instead of pkg_resources
