colcon/colcon-core

- colcon_core/task/python/test/pytest.py
When `pytest` is not being installed invoking `colcon` results in the following exception:
```
ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.python_testing.pytest': No module named '_pytest'
...
from _pytest.main import EXIT_NOTESTSCOLLECTED
ImportError: No module named '_pytest'
```
Since exception is being catched it only results in an error message but doesn't prevent the tool from working. As a temporary workaround installing `pytest` will get rid of the error message.
This patch move the import into a local scope so that it is only being used when a package requests `pytest` and therefore has a dependency on `pytest`.
> make pytest import local to only be used when a package requests it

- .travis.yml
- appveyor.yml
Replaces #3. `codecov` supports uploading multiple coverage reports (e.g. collected on Linux using Travis and on Windows using AppVeyor).
> upload coverage information to codecov

- colcon_core/task/python/test/pytest.py
[This](https://ci.ros2.org/job/ci_windows/4290/console) build failed since the absolute path arrives in `pytest` with the backslashes striped and is therefore being interpreted as a relative path.
> avoid using backslahes on Windows when passing PYTEST_ADDOPTS

- colcon_core/task/python/test/pytest.py
The name has been changed in `pytest` version 3.4.0 (in commit https://github.com/pytest-dev/pytest/commit/cd0b2ace6744f1eee8689ca92b5a8453113bf2c5).
> use same name for cache as newer versions of pytest

- colcon_core/shell/template/command_prefix.bat.em
- colcon_core/shell/template/package.bat.em
- colcon_core/shell/template/package.sh.em
- colcon_core/shell/template/prefix.bat.em
- colcon_core/shell/template/prefix.sh.em
Instead of requiring `COLCON_TRACE` to be set a message is always printed to `stderr` when a file is missing which is supposed to be sourced.
> echo to stderr when sourced file is missing

- colcon_core/package_selection/__init__.py
- test/test_package_selection.py
To provide useful feedback to the user in case this happens.
> enumerate duplicate packages in exception

- colcon_core/task/python/test/pytest.py
- colcon_core/verb/test.py
`pytest` returns different return codes for several causes (see https://docs.pytest.org/en/latest/usage.html#possible-exit-codes). When any of the tests failed that should not be considered an "error" in terms of invoking the `test` verb. This unifies the return value semantic across other types.
Related to colcon/colcon-cmake#3.
> use rc 0 when pytest has failing tests

- colcon_core/package_augmentation/__init__.py
- test/test_package_augmentation.py
To match other options derived from command line arguments and as documented in colcon/colcon.readthedocs.org#5.
> use dash for build/run/test dependencies

- colcon_core/event_handler/console_direct.py
I was under the impression `stderr` would by default be line buffered. That doesn't seem to be the case. Therefore this patch flushes `stderr` the same way as `stdout` a few lines above.
Fixes #27. Connect to colcon/colcon-core#27.
> also force flush on stderr

- colcon_core/command.py
- colcon_core/logging.py
- test/spell_check.words
This provide more debugging information even in the case where the tool was invoked without any custom log level.
> add a log file containing all log messages

- setup.cfg
Before the `colcon_core.python_testing` extensions were not listed in the `extensions` / `extension-point` verbs.
> fix showing Python testing extensions

- colcon_core/command.py
- colcon_core/location.py
- test/test_location.py
Beside the `latest` symlink` this patch introduces a `latest_{verb}` symlink to easily get the latest `build` / `test` logs.
> add verb specific latest symlink

- colcon_core/command.py
Instead of placing it in `$COLCON_HOME/log` it defaults to `./log` within the workspace.
The rational for the change:
* the `'log` folder is much easier to discover
* the `log` folder gets "wiped" with the workspace
* consistency with `build` / `install`: when using different `build` folders for e.g. debug and release builds the same can be done for the `log` folder
> change default log location

- .travis.yml
- colcon_core/task/python/test/pytest.py
- test/spell_check.words
* `-o ...` as of `pytest` version 3.3.0
* `--cov-branch` as of `pytest-cov` version 2.5.0
> use newer pytest(-cov) features only when available

- .travis.yml
- colcon_core/shell/__init__.py
- colcon_core/shell/bat.py
- colcon_core/shell/sh.py
- colcon_core/shell/template/package.sh.em
- colcon_core/shell/template/prefix.bat.em
- colcon_core/shell/template/prefix.sh.em
- colcon_core/shell/template/prefix_chain.bat.em
- colcon_core/shell/template/prefix_chain.sh.em
- test/test_shell.py
- test/test_shell_bat.py
- test/test_shell_sh.py
While not complete (the `.bat` scripts still need to be refactored) I would like to get a first review / feedback if that is the desired result.
> add setup script, rename prefix script into local_setup

- colcon_core/package_discovery/path.py
- colcon_core/package_identification/__init__.py
- colcon_core/package_identification/ignore.py
- test/test_package_discovery_path.py
- test/test_package_identification.py
- test/test_package_identification_ignore.py
Since the semantic of "skip" and "ignore" is different within the command line arguments the exception should follow the same meaning in order to not confuse the developer.
> rename SkipLocationException to IgnoreLocationException

- .travis.yml
#46 bootstrap travis tests failed with `pkg_resources.DistributionNotFound: The 'pytest-rerunfailures' distribution was not found and is required by colcon-core`. This attempts to fix it.
> Travis bootstrap needs pytest-repeat and pytest-rerunfailures

- colcon_core/location.py
To avoid crawling through all log directories when not search through `src` explicitly.
> ignore log directory

- colcon_core/event_reactor.py
- colcon_core/executor/sequential.py
Hoping to have more information at hand when an invocation "hangs" in the future.
> add additional logging into sequential executor and event reactor

- colcon_core/argument_parser/destination_collector.py
Necessary for colcon/colcon-defaults#5. Connect to colcon/colcon-defaults#5.
> allow passing through kwargs in destination collector

- debian/patches/setup.cfg.patch
- setup.py
Everything but straight forward approach to apply a patch during the Debian packaging steps.
The patch removes the optional dependencies which are not available from Debian packages from the `install_requires`.
> remove unavailable dependencies in Debian patch

- colcon_core/command.py
- colcon_core/task/python/test/pytest.py
- test/test_command.py
Fixes #36.
This is an "interesting" approach to monkey patch the change proposed upstream.
I will put this in review for people to try and comment on the patch. Once it is approved the help texts can be updated to mention the space prefix only for cases the the arguments are actually valid options of `colcon`.
> override argument parser to fallback to args rather than options

- colcon_core/task/python/test/pytest.py
Otherwise the `.pytest_cache` directory is being created in each package directory (and not as desired under `build`).
Regression of #66.
> fix Pytest -o cache_dir option

- setup.cfg
- stdeb.cfg
This will address the problem with the Bouncy devel jobs not picking up the `pytest` tests. Basically without it `setup.py test` doesn't find any tests.
This requires `python3-pytest-runner` to be available in Ubuntu Xenial (on all other platforms it is available out-of-the-box). I tried installing the [Bionic Debian](https://launchpad.net/ubuntu/+archive/primary/+files/python3-pytest-runner_2.11.1-1_all.deb) in a Xenial docker which worked without a problem. @tfoote Can you please import this Debian into our bootstrap repo.
> add pytest-runner as dependency

- colcon_core/environment/__init__.py
- colcon_core/shell/__init__.py
- colcon_core/shell/bat.py
- colcon_core/shell/sh.py
- colcon_core/shell/template/prefix.bat.em
- colcon_core/shell/template/prefix.sh.em
- colcon_core/shell/template/prefix_util.py
- colcon_core/verb/build.py
- test/test_environment.py
- test/test_shell.py
- test/test_shell_bat.py
- test/test_shell_sh.py
- test/test_shell_template_prefix_util.py
Addresses #56.
Since the `pkg_names` are not necessary anymore in the `create_prefix_script` function of the `ShellExtensionPoint` I removed the argument from the signature. As a consequence I bumped the extension version accordingly (which is the first time) and its nice to see the extension point versioning mechanism working in action :smirk:
> create file with run deps for each package, use these for sourcing packages in topological order

- colcon_core/task/python/test/pytest.py
- colcon_core/verb/build.py
- colcon_core/verb/test.py
Allows to generate the test results in a different directory than the `build` directory.
> add separate --test-result-base argument

- colcon_core/verb/__init__.py
- colcon_core/verb/build.py
- colcon_core/verb/test.py
- test/test_verb.py
Adding this meta information to the install prefix for #76.
With this change the tool actually prints an error when trying to switch the layout of an existing install prefix.
> add marker for install layout

- colcon_core/shell/__init__.py
Making the file extensions for each shell extension available enables colcon/colcon-ros#29 which avoids hard coding those file extensions.
> expose file extensions covered by a shell extension

- colcon_core/package_identification/python.py
- setup.cfg
Fixes #90.
The first commit declares the minimum version of setuptools required. This only works when using `pip` to install the package. The version dependency can't be specified in the `stdeb.cfg` file since some supported platforms like Ubuntu Xenial don't provide a new enough Debian package of `setuptools`.
The second commit will catch the case where the available `setuptools` version is too old and provide a custom error message describing the problem as well as a way to update the package via `pip`.
> setuptools min version

- colcon_core/event_handler/__init__.py
- colcon_core/event_handler/console_start_end.py
- test/spell_check.words
- test/test_event_handler.py
Instead of just printing the seconds (with two decimals) for it with minutes and potentially hours. Also use two, one or no decimals for the seconds depending on how large the duration is.
> add function to format duration as hours, minutes and seconds

- colcon_core/shell/__init__.py
- test/spell_check.words
- test/test_shell.py
> use preferred encoding to decode environment variables

- colcon_core/logging.py
- colcon_core/package_augmentation/__init__.py
- colcon_core/package_discovery/__init__.py
- colcon_core/package_identification/__init__.py
- colcon_core/shell/__init__.py
- colcon_core/task/python/build.py
- colcon_core/task/python/test/__init__.py
- colcon_core/task/python/test/pytest.py
- colcon_core/task/python/test/setuppy_test.py
- colcon_core/verb/build.py
- colcon_core/verb/test.py
- setup.cfg
- test/test_logging.py
- test/test_package_augmentation.py
- test/test_package_discovery.py
- test/test_package_identification.py
- test/test_shell.py
Additionally set the `pytest` option `filterwarnings: error` so that future deprecation warning will result in a failing CI.
Once this is reviewed and merged I will open similar PRs in the other repos (but plan to go ahead and merge them without an explicit review if nobody objects since their changes will be the same).
> update log.warn (deprecated) to log.warning

- colcon_core/subprocess.py
Removing `e` since it isn't being used in the exception handling block.
> remove unused variable

- .travis.yml
- appveyor.yml
- colcon_core/package_identification/python.py
- setup.cfg
- stdeb.cfg
- test/test_package_identification_python.py
This adds version metadata to the dependencies created by python package identification. 
>Distlib is a library which implements low-level functions that relate to packaging and distribution of Python software. It consists in part of the functions in the packaging Python package, which was intended to be released as part of Python 3.3, but was removed shortly before Python 3.3 entered beta testing.
It seems like distlib is the correct library to use for the parsing functionality. Pip uses distlib as seen [here](https://github.com/pypa/pip/blob/873662179aebbf5eacdf681078f47bbfe5ee6149/src/pip/_vendor/distlib.pyi#L1).
> Update python package identification to use DependencyDescriptor

- colcon_core/package_identification/python.py
I just read a blog [post](http://treyhunner.com/2018/10/asterisks-in-python-what-they-are-and-how-to-use-them/) and was inspired to create a more pythonic solution for this algorithm, thought I'd share.
> Update python incompatible version algorithm to use tuple unpacking

- colcon_core/shell/template/prefix.bat.em
Came across this problem when trying to use a python executable but it was not detected. it was comparing an empty string.
A set is done inside the if statement and evaluated inside the if statement, therefore the variable should use delayed expansion as variable expansion occurs when the if statement is evaluated. 
More info about the topic can be found [here](https://blogs.msdn.microsoft.com/oldnewthing/20060823-00/?p=29993).
> Bug when setting a python executable and it is not used

- colcon_core/argument_parser/__init__.py
- colcon_core/command.py
- colcon_core/entry_point.py
- colcon_core/environment/__init__.py
- colcon_core/event_reactor.py
- colcon_core/executor/__init__.py
- colcon_core/executor/sequential.py
- colcon_core/logging.py
- colcon_core/package_augmentation/__init__.py
- colcon_core/package_discovery/__init__.py
- colcon_core/package_identification/__init__.py
- colcon_core/package_selection/__init__.py
- colcon_core/plugin_system.py
- colcon_core/shell/__init__.py
- colcon_core/shell/template/__init__.py
- colcon_core/subprocess.py
- colcon_core/task/__init__.py
- colcon_core/task/python/test/__init__.py
- colcon_core/verb/build.py
- test/test_flake8.py
* Comply with rule `E252` - missing whitespace around annotated parameter equals.
* Ignoring the new warning `W504` - which is ignored by default.
The following change should be reverted once Python 3.5 support is dropped and f-strings can be used:
* Ignore rule `F841` on lines which contain variables which are only used in string which are being formatted with `.format_map(locals())`.
> update code and flake8 arguments to pass with flake8 3.6.x / pycodestyle 2.4.x

- colcon_core/shell/template/package.sh.em
Addresses the problem reported in https://github.com/ros-infrastructure/ros_buildfarm/pull/585#discussion_r228625674 that a `.sh` snippet uses `typeset` which is bash specific.
> replace 'typeset' usage in sh with 'command'

- test/spell_check.words
- test/test_flake8.py
Otherwise the `pydocstyle` logger uses an effective level of 1 flooding the output with debug messages.
> explicitly set log level of pydocstyle

- colcon_core/shell/__init__.py
- test/test_shell.py
Handle some cases where environment variable are consisting of multiple lines, e.g.:
```
BASH_FUNC_module%%=() {  _moduleraw "$@" 2>&1
}
```
The patch won't do the right thing for multiline variables where the following lines still look like "key=value":
```
FOO="bar
BAZ=qux"
```
An alternative would be to use a different separator (e.g. using `env -0`) but that option is not available on macOS.
> handle multiline environment variables

- colcon_core/location.py
- test/spell_check.words
- test/test_location.py
~~Maybe addressing~~ Fixes #129.
The patch ensures that the log directory doesn't exist yet. If it does a serial number is appended until it doesn't.
Without the patch two invocations started in the same second were writing to the same log directory.
> create unique log directory, avoiding race

- colcon_core/shell/template/hook_prepend_value.sh.em
- colcon_core/shell/template/package.sh.em
Since the function can't be unset (as described in the touched comment) it should be prefixed with an underscore so that it doesn't appear in the completion when typing `colco<tab>`.
> underscore prefix shell function which can't be unset

- colcon_core/location.py
- test/test_location.py
This adds symlink creation for Windows for 'latest {Verb}'. Currently os.symlink only works when run with administrator privileges and it will throw an OSError if symlink privileges are not available.
> Enabling symlink creation on Windows

- colcon_core/environment/__init__.py
This updates an import statement with regards to the collections deprecated namespace.
This addresses issue #136
> collections.abc

- colcon_core/executor/__init__.py
- colcon_core/executor/sequential.py
- test/test_executor.py
- test/test_executor_sequential.py
Adds an `OnError` enum to offer more fine grain control about the executor behavior in case a job fails. The new keyword argument is introduced in a backward compatible way so that existing code calling the global function `colcon_core.executor.execute_jobs` as well as existing `ExecutorExtensionPoint.execute` methods continue to work.
The patch does neither modify the verbs to make use of the additional on-error values nor the executors to make use of the new keyword argument.
> add OnError enum to configure the executor behavior when a job fails

- colcon_core/executor/sequential.py
- colcon_core/verb/build.py
- colcon_core/verb/test.py
- test/test_executor_sequential.py
Builds on top of #144.
Adds an option `--continue-on-error` to the `build` verb and uses the `on_error` argument in the `build` and `test` verbs as well as the sequential executor to avoid using deprecated API.
> use OnError enum/arg in verbs and executor

- colcon_core/package_selection/__init__.py
- colcon_core/verb/__init__.py
- colcon_core/verb/build.py
- colcon_core/verb/test.py
- test/test_flake8.py
These changes came up while working on other stuff:
* Refactor `update_object` to be reused across verbs.
* Clarify the order of the data in the parameter.
* Nitpick line wrapping change.
> Refactorings / cleanup

- .travis.yml
The latest release of `pytest-rerunfailures` version 6.0 requires `pytest` 3.8 or higher.
> support latest pytest-rerunfailures release

- colcon_core/task/__init__.py
- colcon_core/task/python/build.py
- test/test_task.py
Fix the logic for the case where the `dst` symlink exists but points to a not existing `src`.
> fix symlink replacement logic

- test/spell_check.words
- test/test_copyright_license.py
The same spelling mistake is present in all other packages. For those it will be fixed with the transition to `scspell`.
> fix spelling of test function

- colcon_core/task/__init__.py
- colcon_core/task/python/build.py
- test/test_argument_parser.py
- test/test_executor.py
To pass with recent releases of flake8 et al.
The remaining style warnings `N803` are false-positives which will hopefully be resolved in a future patch release of `pep8-naming` (anything > 0.8.0).
> comply with stricter style checks

- colcon_core/task/python/test/pytest.py
Intent is to provide consistent behavior when pytest extensions aren't present.
> Handle missing pytest_cov gracefully

- colcon_core/package_descriptor.py
This improves the topological ordering performance, reducing package listing times by about 15% in my trials.
> Switch descriptor filter to list comprehension

- colcon_core/package_descriptor.py
`d is str` is always `False` here, so we're getting a mixture of `DependencyDescriptor` and `str` from `get_dependencies`.
> Fix DependencyDescriptor conversion in get_dependencies

- colcon_core/topological_order.py
This provides consistent behavior between `get_dependencies()`, `get_recursive_dependencies()` and `.dependencies[foo]`, which all represent dependencies using the `DependencyDescriptor` type. The inheritance already used on the `DependencyDescriptor` type should ensure that this won't break any existing uses of `PackageDecorator.recursive_dependencies`.
> Store DependencyDescriptor in recursive_dependencies

- colcon_core/package_descriptor.py
Store dependency distances on `DependencyDescriptor`s
The distance measures the smallest number of steps that each recursive dependency is from the package.
Depends on #173
Depends on #174
> Store dependency distances on DependencyDescriptors

- colcon_core/shell/template/prefix_util.py
- test/test_shell_template_prefix_util.py
Before this patch:
```
$ docker run -it --rm osrf/ros2:nightly
mkdir -p /tmp/foo/src && cd /tmp/foo
colcon build --merge-install
source install/setup.bash
File "/tmp/foo/install/_local_setup_util.py", line 137, in <module>
main()
File "/tmp/foo/install/_local_setup_util.py", line 18, in main
packages = get_packages(Path(__file__).parent, args.merged_install)
File "/tmp/foo/install/_local_setup_util.py", line 42, in get_packages
for p in (prefix_path / subdirectory).iterdir():
File "/usr/lib/python3.6/pathlib.py", line 1081, in iterdir
for name in self._accessor.listdir(self):
File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: …
```
> fix sourcing empty workspace built with `--merge-install`

- colcon_core/executor/sequential.py
To avoid deprecation warning in Python 3.7+:
> colcon_core\executor\sequential.py:94: PendingDeprecationWarning: Task.all_tasks() is deprecated, use asyncio.all_tasks() instead
> use new asyncio.all_tasks if available

- colcon_core/task/python/test/pytest.py
- setup.cfg
- test/test_entry_point.py
- test/test_executor.py
- test/test_logging.py
- test/test_package_descriptor.py
- test/test_package_identification_python.py
- test/test_plugin_system.py
- test/test_shell.py
- test/test_shell_bat.py
- test/test_shell_sh.py
This patch fixes #196 and addresses the failing CI due to the recent release of `pytest` 5.0. The change is backward compatible with older `pytest` versions.
* The first commit uses the new exit code constants.
* The second commit updates the use of the `ExceptionInfo` (which changes in pytest-dev/pytest#5412)
* The third commit ignores the new deprecation warnings.
> support pytest 5.0+

- colcon_core/task/python/build.py
> fix syntax in error case

- colcon_core/shell/template/prefix.bat.em
It seems to be a regression after https://github.com/colcon/colcon-core/pull/209, where it removed `enabledelayedexpansion` for `_colcon_run_ordered_commands` but forgot to revert the delay expansion usage. As a result, whenever the generated `local_setup.bat` runs, it throws out `error: unable to find python executable` even the Python executable exists.
> [Windows] Use default expansion for _colcon_python_executable

- colcon_core/task/python/build.py
We already work around easy-install.pth since https://github.com/colcon/colcon-core/pull/163, so may as well stop using it entirely.
> Stop using easy-install.pth

- colcon_core/task/python/build.py
Normally when running setup.py install, python makes a bdist egg, so we need to use the bdist_egg to control where it gets generated (outside the source tree).
But since we're using --single-version-externally-managed, this is no longer required.
Also added test coverage to ensure that my code is correct.
~~fixes #226~~
On third though, actually fixes #226
> Don't make bdist_egg

- colcon_core/command.py
- setup.cfg
This environment variable provide a way to specify warnings filter which are scoped to modules matching the regular expression `colcon.*`. Using `PYTHONWARNINGS` directly isn't possible since it doesn't support using a regular expression: see https://bugs.python.org/issue34624.
> add COLCON_WARNINGS environment variable

- colcon_core/package_identification/python.py
Detected using this new feature: colcon/colcon-core#232.
> use non-deprecated logger API

- colcon_core/shell/template/__init__.py
Otherwise if the destination already exists and is a symlink the evaluated template will be written to the symlink instead of to the actual destination. Since changing the content of the symlinked file is undesired the symlink needs to be unlinked before.
> unlink existing symlink before writing evaluate template content to file

- setup.cfg
Introduced by #230.
Found when packaging for Fedora 29 and EPEL 7, which package pytest 3.6.4 and 2.9.2 respectively. I'll have to skip these tests on those platforms.
It is noteworthy that neither Bionic nor Cosmic meet this requirement either.
> Clarify new pytest version requirement

- colcon_core/shell/template/prefix_util.py.em
By always adding the key with the `path_without_ext` it ensures that the later logic check for the presence of a `.dsv` file - even if there is no file with the basename for the specific shell.
> always consider .dsv files, even when no shell specific script exists

- setup.cfg
- test/test_build_python.py
Reverts #243 and avoids the use of `tmp_path` introduced by #230 instead.
Easier to read whitespace-ignoring diff: https://github.com/colcon/colcon-core/pull/246/files?w=1
@rotu FYI.
> avoid requiring tmp_path introduce in pytest 3.9.0

- colcon_core/shell/template/prefix_util.py.em
To add context, when working with Java projects it can happen that a package produces multiple jar files that should be added to the `CLASSPATH` environment variable.
Example .dsv file for `rcljava_common`:
```
prepend-non-duplicate;CLASSPATH;share/rcljava_common/java/commons-lang3-3.7.jar;share/rcljava_common/java/slf4j-api-1.7.21.jar;share/rcljava_common/java/log4j-1.2.17.jar;share/rcljava_common/java/slf4j-log4j12-1.7.21.jar;share/rcljava_common/java/slf4j-jdk14-1.7.21.jar;share/rcljava_common/java/rcljava_common.jar
```
> Add support for prepending multiple values to env variables from .dsv files

- colcon_core/shell/__init__.py
Fixes #248 
On Windows any of the following characters is allowed in an environment variable name (to my knowledge):
* lower alpha
* upper alpha
* digit
* underscore
* and the special characters not allowed on non-Windows:
* percent (for dynamic names I guess)
* `(){}[]$*+-\/"#',;.@!?`
For non-Windows the patch removes the `%` character (which was only added for Windows in the first place) as well as enforce that the first character is not a digit.
> support more characters in environment variable names on Windows

- colcon_core/package_identification/python.py
- test/test_package_identification_python.py
Prevents reading only the `setup.cfg` file when the `setup()` call in the `setup.py` file contains more information.
In this case the [colcon-python-setup-py](https://github.com/colcon/colcon-python-setup-py) should be used to identify the Python and collect its information.
> check that no arguments are passed to the setup() function in setup.py

- colcon_core/task/python/build.py
Prevent crashes such as:
https://github.com/colcon/colcon-python-setup-py/pull/24#issuecomment-545664031
> Allow setup py data to contain Nones

- colcon_core/package_descriptor.py
Refactoring the list comprehension within the loop into a once populated dict of sets is significantly cheaper for larger workspaces.
For an example ROS 2 workspace with 268 pkgs the time to `list` goes down by roughly 10% (from 2.25s to 2.05s).
> avoid repeated list comprehension

- colcon_core/topological_order.py
Refactoring a set of `DependencyDescriptor`s to a set of `str` were sufficient.
For an example ROS 2 workspace with 268 pkgs the time to list goes down by roughly 10% (from 2s to 1.8s).
> use a plain str where sufficient

- colcon_core/shell/__init__.py
- colcon_core/shell/bat.py
- colcon_core/shell/sh.py
- colcon_core/shell/template/prefix_util.py.em
This resolves an issue where environment variables can collide if modified by both .dsv files and scripts.
For more detail see https://github.com/ament/ament_package/issues/103
The solution is to always prepend, which will avoid overwriting a variable if previously set by a script.
Then we introduce a cleanup command for each variable prepended to in order to remove a possible trailing separator.
I've implemented the new "trailing separator cleanup" command for sh. Opening this PR for early feedback while I figure out the equivalent bat and powershell commands.
Open to better naming suggestions.
> Always prepend with a trailing separator

- colcon_core/shell/sh.py
Follow up of #254 fixing the logic in sh/bash.
> fix command to remove trailing separator

- colcon_core/command.py
- colcon_core/location.py
- test/test_location.py
The patch fixes #263 which reports a few problems around the logging base path:
* `COLCON_LOG_PATH` is consider when `--log-base` is not passed explicitly
* `--log-base` supports passing `os.devnull`
* the docs of `COLCON_LOG_PATH` state the correct default value which is supposed to be `./log`
It also updates the test to check explicitly for the desired precedence order.
> fix setting log base path

- bin/colcon
- colcon_core/command.py
- setup.cfg
This environment variable was never actually used / checked. Since the log directory is only created after the arguments have been passed the existing `--log-base` argument can be used in all cases.
> remove unused COLCON_LOG_PATH env var

- colcon_core/task/python/build.py
#219 introduced a regression for Python packages which don't store their first level Python package in a direct subdirectory below the `setup.py` file (it passes something like this in the `setup()` function: `package_dir={'': 'somewhere'}`).
When building with `--symlink-install` the `easy-install.pth` file (which was removed by the referenced PR) made sure that the Python package was found in the source directory of the package. With it being removed the fallback was used which is the `build` directory being part of the `PYTHONPATH`.
For packages as described above that `PYTHONPATH` entry pointing to the packages build directory is incorrect. It needs to point to the subdirectory from where the Python packages can be found - in the above example that would be `<pkg-build>/somewhere`.
> fix environment for symlinked Python package which have their sources in a subdirectory

- colcon_core/command.py
- test/test_command.py
Otherwise hitting Ctrl-C before the verb execution has started results in a stacktrace.
> catch KeyboardInterrupt before verb is invoked

- colcon_core/shell/template/prefix_util.py.em
Which allows to group multiple lines if a `dsv` file updates more than one environment variable.
> skip empty lines in dsv files

- colcon_core/shell/template/prefix_util.py.em
Instead of showing a stacktrace print the filename and line number as well as a description what content was expected.
> improve error message when split for dsv line raises

- colcon_core/shell/template/prefix_util.py.em
_prepend_unique_value fails to initialize env_state if the environment
variable is the empty string. Instead, it should treat missing and
empty variables identically, just like the shell does.
> fixed KeyError in _prepend_unique_value

- colcon_core/package_descriptor.py
- colcon_core/package_discovery/path.py
- test/test_package_discovery_path.py
Instead of showing the user the realpath this change only uses the realpath for the de-duplication of found package descriptors. Package paths shown by e.g. `colcon list` show a more intuitive path like `src/pkgname` rather than an absolute path or even a path outside the workspace after resolving symlinks.
> apply realpath only for deduplication, keep original path for UI

- colcon_core/executor/__init__.py
- colcon_core/shell/__init__.py
- colcon_core/subprocess.py
- test/test_executor.py
- test/test_subprocess.py
As of Python 3.8 the `asyncio` `CancelledError` is not the same as the one from `concurrent.futures` anymore.
I think this addresses the same problem as #245 for the `subprocess` modules but also the same issue in the `executor` module.
> use CancelledError from asyncio instead of concurrent.futures for Python 3.8

- test/test_executor.py
Follow up of #284 
`asyncio.CancelledError` is not an `Exception` but only a `BaseException`.
> fix test to raise asyncio.CancelledError

- colcon_core/argument_default.py
- colcon_core/package_discovery/path.py
Together with the referenced PRs this addresses #274.
Add concept of wrapped default values in order to distinguish them from explicitly passed arguments. The wrapped values aim to have as similar behavior as possible to the original value type.
> wrap default value to distinguish from explicitly passed arguments

- colcon_core/task/python/test/pytest.py
Allows to force coverage information for Python packages using `pytest` even if they don't declare an explicit test dependency on `pytest-cov`.
> add --pytest-with-coverage option

- .travis.yml
- colcon_core/task/python/test/pytest.py
- debian/patches/setup.cfg.patch
- setup.cfg
- stdeb.cfg
As of `setuptools` 41.5.0 invoking tests through the `setup.py` file is deprecated (see pypa/setuptools#1878):
> WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
This PR only changes the `pytest` based testing extension.
> invoke pytest directly instead of through the setup.py file

- colcon_core/task/python/test/setuppy_test.py
As of `setuptools` 41.5.0 invoking tests through the `setup.py` file is deprecated (see pypa/setuptools#1878):
> WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
This PR changes the `unittest` based testing extension. Similar to #296 which does the same for `pytest`.
Additionally the patch adds `--unittest-args` to allow passing arbitrary arguments to `unittest`.
> invoke unittest directly instead of through the setup.py file

- colcon_core/task/python/build.py
Since a parent directory of `dst` might be symlinked to the source directory the `islink` check in the `if` isn't sufficient. The other cases still need to make sure that `dst` is not actually the same file as `src` before deleting it.
Fixes #300.
> fix symlink logic to not delete files in src

- bin/colcon
- colcon_core/entry_point.py
- colcon_core/plugin_system.py
- test/entry_point_context.py
This allows avoiding to load undesired entry points.
> add exclude argument to load_entry_points

- colcon_core/dependency_descriptor.py
On a large workspace with ~300 pkgs this patch reduces the time for `colcon list` from ~1.0s to ~0.9s.
Profiling the `get_recursive_dependencies()` function shows that from ~370ms before ~310ms where spent in `deepcopy()`. With this change the `deepcopy()` part is reduced to 110ms.
> improve performance deepcopying DependencyDescriptors

- colcon_core/command.py
E.g. the help messages for the obsolete arguments from colcon/colcon-package-information#28.
> shorten prog to basename if on PATH

- colcon_core/task/python/test/__init__.py
If `setup_py_data['tests_require'] is None`, don't crash
> Fix crash in has_test_dependency

- colcon_core/task/python/test/pytest.py
Similar to https://github.com/ament/ament_lint/pull/220
I've change the `skip` attribute by "skipped", remove the non permitted `status` attribute and following the same logic exposed in [this comment](https://github.com/ament/ament_lint/pull/220#issuecomment-597765930) I changed `failures` by `errors`.
> Generate xunit files valid for the junit10.xsd

- colcon_core/task/python/test/pytest.py
Related to https://github.com/colcon/colcon-mixin-repository/pull/21
no print to stderr
```
root@434b2f50580b:~/ws# colcon test --packages-select sros2 --pytest-with-coverage --pytest-args --cov-report=term
Starting >>> sros2   
Finished <<< sros2 [2.84s]          
Summary: 1 package finished [3.04s]
```
Example output in stdout:
```
----------- coverage: platform linux, python 3.8.2-final-0 -----------
Name                               Stmts   Miss Branch BrPart  Cover
--------------------------------------------------------------------
setup.py                              13     13      4      0     0%
sros2/__init__.py                      9      2      4      1    62%
sros2/api/__init__.py                271     58     60      8    73%
sros2/command/__init__.py              0      0 …
```
> print python coverage results to console

- colcon_core/task/python/test/pytest.py
Reverts colcon/colcon-core#331 - see https://github.com/colcon/colcon-core/pull/331#issuecomment-606892768.
> Revert "print python coverage results to console"

- colcon_core/task/__init__.py
- colcon_core/task/python/build.py
- colcon_core/task/python/test/pytest.py
- colcon_core/task/python/test/setuppy_test.py
- test/test_task.py
> deprecate colcon_core.task.check_output()

- colcon_core/package_identification/python.py
E.g. https://build.osrfoundation.org/job/ros_gazebo_pkgs-ci-default_kinetic-xenial-amd64/110/ fails with:
```
ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.package_identification.ros': No module named 'setuptools.config', 'setuptools' needs to be at least version 30.3.0, if a newer version is not available from the package manager use 'pip3 install -U setuptools' to update to the latest version
File "/usr/lib/python3/dist-packages/colcon_core/entry_point.py", line 101, in load_entry_points
extension_type = load_entry_point(entry_point)
File "/usr/lib/python3/dist-packages/colcon_core/entry_point.py", line 143, in load_entry_point
return entry_point.load()
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", …
```
> make import locally to avoid failures when not even being used

- colcon_core/command.py
- colcon_core/pytest/hooks.py
- setup.cfg
To avoid using the same redirect in non-colcon pytest invocations the custom hook is only changing the behavior when the environment variable `COLCON` is set.
> use pytest hook to redirect pytest warnings to stderr

- colcon_core/pytest/hooks.py
Defaulting these unused arguments will make the hook compatible with older versions of pytest.
> Improve pytest hook compatibility

- colcon_core/package_identification/ignore.py
- colcon_core/verb/build.py
As per https://github.com/ros-infrastructure/rep/pull/256
> Allow ignore_marker to be a dangling symlink

- codecov.yml
Otherwise commits are marked with :x: when coverage thresholds aren't met (which the package currently doesn't require / enforce) and it is difficult to see if a commit has actual test failures.
> make CodeCov results informational, not affecting status

- colcon_core/shell/template/prefix.bat.em
In the `local_setup.bat`, it first attempt to use the Python binary decided at compile time. If it doesn't exist, it will then test the first one visible from `%PATH%`. In the cases of no Python in the `%PATH%`, it will error on with `error: unable to find python executable`.
However, in my setting, I don't have any Python binary in `%PATH%`, but I do have the Python binary under `@(python_executable)` which decided at the compile time. By the logic, it should firstly find that one, but it error out with `error: unable to find python executable` instead.
After digging, it turned out that when accessing the variable is set within a FOR loop or IF block, one have to turn on `setlocal enabledelayedexpansion` and use `!_colcon_python_executable!` to access the values. This pull request is to …
> [windows] fix _colcon_python_executable fallback code path.

- colcon_core/event_reactor.py
- test/test_event_reactor.py
This allows event handlers to reduce the clutter when known problems occur.
> suppress stacktrace for RuntimeError raised by event handler

- colcon_core/subprocess.py
To improve the information in case of issues like #352.
> show stderr output if check_output() fails

- colcon_core/event_handler/console_start_end.py
To provide the same context information as for successful jobs.
> show the duration for aborted and failed jobs

- colcon_core/environment/pythonpath.py
- colcon_core/task/python/build.py
Fixes  colcon/colcon-python-setup-py#38.
See https://setuptools.readthedocs.io/en/latest/history.html#v49-2-0
> avoid warning introduced in setuptools 49.2.0

- colcon_core/subprocess.py
Depending on the timing a `KeyboardInterrupt` can be raise in this location which leads to a stacktrace and incomplete termination.
> catch KeyboardInterrupt in another case to avoid stacktrace

- colcon_core/shell/template/__init__.py
The Python packages `empy` (needed by `colcon` for templates) and `em` have the same namespace. If the latter is installed the former will not be usable, see e.g. https://answers.ros.org/question/359578/colcon-build-symlink-install-cant-find-__main__-module-ld-cannot-find-lpthreads/ The import could also fail if `empy` is just not installed.
This patch aims to provide an improved error message for the failing import to distinguish these cases.
> improve error message when em.* can't be imported, suggest collision between empy and em

- colcon_core/task/python/build.py
It seems setuptools doesn't like `--egg-base` to be an absolute path. Example with setuptools 45.2.0 (Ubuntu Focal):
```
--- stderr: canopen
error: Error: setup script specifies an absolute path:
/home/administrator/ws/build/canopen/canopen.egg-info/PKG-INFO
setup() arguments must *always* be /-separated paths relative to the
setup.py directory, *never* absolute paths.
---
Failed   <<< canopen [1.41s, exited with code 1]
```
The error goes away if I compute the `--egg-base` argument as a path relative to the cwd, as in this PR.
> Pass --egg-base as relative.

- appveyor.yml
- colcon_core/__init__.py
- test/test_flake8.py
**AppVeyor:**
* The first commit fixes #401.
* The second commit avoids another warning on AppVeyor about the `pip` version being outdated.
**Travis CI:**
* The fourth commit fixes #400 which only occurs if there are flake8 error (so it doesn't appear in passing CI builds).
* The third commit adds a linter error to check the fourth commit. The fifth commit reverts that linter error again.
> fix warnings in CI

- colcon_core/shell/template/package.sh.em
- colcon_core/shell/template/prefix.sh.em
- colcon_core/shell/template/prefix_chain.sh.em
This allows to pipe the `COLCON_TRACE=1` output of the setup scripts to a file. Sourcing that file should result in the same environment change as sourcing the original setup file *if* the starting environment was the same - but it does so in a fraction of the time.
> make COLCON_TRACE output of sh sourceable

- colcon_core/task/python/build.py
Idea from https://github.com/colcon/colcon-core/pull/386/files#r495217794
Some symlinks are needed by setup.py for packages renamed via
`packages_dir`, but can be discarded after. Discarding them makes sure the
renamed modules aren't importable by their unrenamed name.
Without this PR
```
>> import bob
Hello from bob
>>> import lib
Hello from bob
```
With this PR
```
>>> import bob
Hello from bob
>>> import lib
File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'lib'
```
> Remove unnecessary symlinks after building modules renamed by packages_dir

- bin/colcon
The regression was introduced in #385 when some functionality was extracted from the Python identification extension into a new Python augmentation extension. This patch makes sure that new extension is available during bootstrapping.
> fix bootstrapping not using new Python augmentation extension

- colcon_core/task/python/build.py
Fix regression introduced in #387 when the package source dir is a symlink.
@mikepurvis FYI.
> fix regression when package dir is symlinked

- colcon_core/task/python/build.py
This bug can be demonstrated using the macOS Catalina virtual environments in GitHub Actions, where it appears that the working directory is under a symlink.
Regression caused by #406
> Fix regression when enitre workspace is symlinked

- .travis.yml
- appveyor.yml
* On Linux check: Python 3.5 - 3.8 (all used by actively supported distros)
* On Windows (since it is a rolling release) only check the latest: Python 3.8
> add more Python versions to the test matrix

- test/test_build_python.py
If the build does fail, it would be good to have an earlier indication of where things went awry.
This function appears to return `None` on success, or an error code value on failure.
> Assert that the Python build actually succeeds

- colcon_core/command.py
- colcon_core/executor/__init__.py
I think it is acceptable to catch a generic Exception in both
places where the error is being reported.
In the command.py, we could use the exception type
`warnings._OptionError`, but I don't think it's safe to rely this
private exception type as it might not remain stable in future.
It would be better to not call the private function altogether,
but I'm not sure how best to avoid it.
In executor/\_\_init\_\_.py, we are propagating the exception in the
except block. In this case, I consider the linter is reporting a false-positive,
as it is unable to handle this situation.
---
This should fix recent CI failures, [for example](https://travis-ci.org/github/colcon/colcon-core/jobs/753488935).
> Suppress blind exception flake8 errors

- colcon_core/shell/template/prefix.bat.em
An un-escaped closing parentheses will break the for loop that is using this value.
This same fix was already implemented in ament/ament_package#91.
> Escape closing parenthesis in prefix.bat file

- colcon_core/package_discovery/__init__.py
- colcon_core/package_discovery/path.py
- test/test_package_discovery.py
- test/test_package_discovery_path.py
Fixes #438
If the `--paths` value is not provided through the shell, then shell wildcards won't be expanded. This is the case when using a `defaults.yaml` file.
To cover this case, expand wildcards on all platforms, not just Windows. I renamed and made `expand_wildcards` part of the public API so that it can be used elsewhere as well.
I can't think of any downsides to doing this, and being able to use wildcards in a `defaults.yaml` file does seem like a very normal use case.
Signed-off-by: Christophe Bedard <bedard.christophe@gmail.com>
> Expand shell wildcards in --paths for all platforms

- colcon_core/package_augmentation/python.py
- colcon_core/task/python/test/__init__.py
- test/test_package_identification_python.py
- test/test_task_python_test_pytest.py
It's becoming an increasingly common pattern to declare test dependencies using [options.extras_require]test. This change merges the test dependencies declared using that mechanism with any discovered using [options]test_requires.
This is more-or-less a follow-up to #444.
> Extract test dependencies from options.extras_require.test

- setup.cfg
- test/test_argument_parser.py
- test/test_command.py
- test/test_entry_point.py
- test/test_environment.py
- test/test_environment_path.py
- test/test_environment_pythonpath.py
- test/test_event_handler.py
- test/test_event_handler_console_direct.py
- test/test_event_handler_console_start_end.py
- test/test_event_handler_log_command.py
- test/test_event_reactor.py
- test/test_executor.py
- test/test_location.py
- test/test_logging.py
- test/test_package_augmentation.py
- test/test_package_decorator.py
- test/test_package_discovery.py
- test/test_package_discovery_path.py
- test/test_package_identification.py
- test/test_package_identification_ignore.py
- test/test_package_selection.py
- test/test_plugin_system.py
- test/test_prefix_path.py
- test/test_shell.py
- test/test_shell_template.py
- test/test_shell_template_prefix_util.py
- test/test_task.py
- test/test_verb.py
The standalone 'mock' package is a [backport of unittest.mock from Python 3.3](https://pypi.org/project/mock/). All versions of Python that colcon supports have unittest.mock, so it's better to use that and drop the unnecessary test dependency.
> Switch to unittest.mock

- colcon_core/package_augmentation/python.py
- test/test_package_identification_python.py
I'm not sure the precise circumstances that lead to this, but I'm seeing 'None' coming out of options.extras_require entries in the wild.
Regression caused by #450
> Handle 'None' in options.extras_require

- codecov.yml
Computing coverage for a branch is important for comparing with pull requests, but getting a big fat X in the commit logs when the coverage decreases slightly or is noisy isn't helpful. Since the 'project' configuration is already marked as 'informational', it will still run for branch CI but won't cause the nasty red X if things aren't perfect.
The patch coverage information isn't really very useful on branch CI, so this PR suggests that we stop computing it except in PRs where we want a regression to be asserted.
Relevant docs: https://docs.codecov.com/docs/commit-status#only_pulls
> Prevent branch CI from failing because of coverage changes

- colcon_core/verb/build.py
Overriding packages in underlay workspaces appears to be more common than originally believed, so it's a good idea to let the dust settle as a warning rather than breaking builds at this point.
> Demote package override error to a warning

- debian/patches/setup.cfg.patch
Release regression caused by #444
> Update debian patch after changes to setup.cfg

- bin/colcon
Fix an issue from #449 - the bootstrap from source instructions are failing with the following error
```
[0.267s] ERROR:colcon.colcon_core.shell:Exception in shell extension 'sh': get_entry_points() not overridden for group 'colcon_core.shell.find_installed_packages'
File "/home/sloretz/ws/colcon-from-source/src/colcon-core/colcon_core/shell/__init__.py", line 298, in get_command_environment
return await extension.generate_command_environment(
File "/home/sloretz/ws/colcon-from-source/src/colcon-core/colcon_core/shell/sh.py", line 137, in generate_command_environment
check_dependency_availability(
File "/home/sloretz/ws/colcon-from-source/src/colcon-core/colcon_core/shell/__init__.py", line 510, in check_dependency_availability
packages_in_env = …
```
> Setup find_installed_packages to fix bootstrap instructions

- .github/workflows/ci.yaml
Installing the test dependencies like this also enables importing from the package itself, which is contrary to the bootstrapping scenario we're trying to test. Simplest solution is to specifically uninstall it again, which should leave all of the dependencies in place.
Additionally, the test results during the bootstrap build were not causing the action to fail, and were therefore being ignored.
Furthermore, it appears that the `COLCON_ALL_SHELLS` variable is not sufficient to generate usable bash hooks on Windows, so I'm disabling the bash test until we can come up with a good way to support it. It wasn't tested in the old Travis tests, and documentation suggests that it isn't a supported scenario anyway.
Lastly, while in the package root, it's possible to perform imports from …
> Fix the bootstrap test in GitHub Actions

- colcon_core/package_selection/__init__.py
This change adds a PRIORITY attribute to package selection extensions, and considers it when ordering the extensions for use.
This is a backwards-compatible change because all existing extensions will inherit the default priority value and will continue to be sorted alphabetically within that priority level.
> Prioritize package_selection extensions

- colcon_core/environment/pythonpath.py
- colcon_core/task/python/build.py
- test/spell_check.words
- test/test_environment_pythonpath.py
The distutils package is deprecated and will be removed in Python 3.12. We can achieve the same behavior using sysconfig directly.
> Use sysconfig directly to determine python lib dir

- colcon_core/package_identification/python.py
- test/spell_check.words
Fix deprecations introduced in [setuptools V61.0.0](https://setuptools.pypa.io/en/latest/history.html#v61-0-0)
```
/home/user/colcon-venv/lib/python3.10/site-packages/setuptools/config/__init__.py:28: SetuptoolsDeprecationWarning: As setuptools moves its configuration towards `pyproject.toml`,
`setuptools.config.read_configuration` became deprecated.
For the time being, you can use the `setuptools.config.setupcfg` module
to access a backward compatible API, but this module is provisional
and might be removed in the future.
```
> fix deprecated setuptools.config.read_configuration

- colcon_core/package_augmentation/python.py
- test/spell_check.words
- test/test_package_identification_python.py
This information could be useful to other extensions.
> Add package maintainer information to metadata

- colcon_core/verb/build.py
- test/spell_check.words
This functionality is being moved to a separate colcon extension, [colcon-override-check](https://github.com/colcon/colcon-override-check).
Reverts part of #449
> Move the package package override checks out of colcon-core

- stdeb.cfg
The retest and rerunfilures packages are new to Ubuntu. All three of these pytest plugins are 'soft' dependencies. The code will gracefully handle their absence.
https://www.debian.org/doc/debian-policy/ch-relationships.html#binary-dependencies-depends-recommends-suggests-enhances-pre-depends
https://github.com/astraw/stdeb#stdebcfg-configuration-file
https://packages.ubuntu.com/search?keywords=python3-pytest-cov&searchon=names&suite=all&section=all
https://packages.ubuntu.com/search?keywords=python3-pytest-repeat&searchon=names&suite=all&section=all
https://packages.ubuntu.com/search?keywords=python3-pytest-rerunfailures&searchon=names&suite=all&section=all
> Make pytest plugins 'Recommended' in debian package

- stdeb.cfg
These extensions are not packaged for Ubuntu Bionic or Focal, and while it's still possible to install colcon with these recommendations present, the package is excluded from a normal 'apt upgrade' because of their absence. A 'dist-upgrade' works as expected, but we still want users to be able to upgrade normally.
Fixes: #495
> Demote uncommon pytest extension packages to suggestions

- colcon_core/subprocess.py
- colcon_core/task/__init__.py
This PR adds the output of running a process to the `stdout` and `stderr` fields of the returned [subprocess.CompletedProcess](https://docs.python.org/3/library/subprocess.html#subprocess.CompletedProcess).
The rationale for this change is that because when running some build tools (e.g. Rust's `cargo`), they don't save their output to a file, so it's not possible to expose their results to `colcon` (e.g. saving test results for `colcon test-result`)
> Capture stdout and stderr

- debian/patches/setup.cfg.patch
This pytest plugin has always been optional in colcon. A recent change made it an optional debian dependency as well. This change updates the corresponding patch to ensure that pkg_resources doesn't complain if colcon is used when it is absent.
Fixes: #495
> Update debian patch to make pytest-cov optional

- colcon_core/pytest/hooks.py
The nonlocal declaration is only needed when a variable is assigned to within a tighter scope. If the variable is only referenced but is not defined within the scope, Python should look for it in the higher scope without the declaration.
This change makes colcon-core's pytest hook compatible with Python 2. This is necessary to invoke Python 2 pytest while colcon is in a user's `PYTHONPATH`, where we're currently seeing a syntax error.
> Drop unneeded nonlocal from pytest hook

- colcon_core/python_install_path.py
- colcon_core/task/python/build.py
- test/spell_check.words
Fixes #506
This PR avoids `--install-layout deb` and `deb_system`. I suspect these were never used before #504, and they have at least one bug that makes them unsuitable for colcon.
More info here: https://github.com/colcon/colcon-core/issues/506#issuecomment-1113874558
> Avoid deb_system and --install-layout deb

- colcon_core/python_install_path.py
Similar to what Debian did when Ubuntu Jammy shipped, Fedora has patched CPython to override the installation directory for Python packages, presumably to avoid collision with the system-packaged Python modules.
Fedora's approach is slightly different, but can be patched around in a similar way.
Here's Fedora's patch: https://src.fedoraproject.org/rpms/python3.10/blob/fdfd6c1d945a381cbc85aa6d60b2369ac3ce7f50/f/00251-change-user-install-location.patch
Similar to #504
> Add workaround for Fedora's rpm_prefix distribution patch

- colcon_core/task/python/build.py
- colcon_core/task/python/template/__init__.py
- colcon_core/task/python/template/sitecustomize.py.em
- setup.cfg
- test/spell_check.words
During initialization, the `site` module probes for a `sitecustomize` module which performs site-specific initialization of various paths.
Python virtual environments modify sys.prefix in order to ensure that any attempted package installation ends up using the virtual environment instead of the system locations.
This approach should prevent various Linux distributions' attempts to inject `local` into the installation locations for python packages. They seem to have special cases for detecting virtual environments and omit the custom logic when detected.
This is a potentially disruptive change. It modifies some of the core installation logic for python packages. However, some popular Linux distributions (Looking at you, [Debian](https://salsa.debian.org/cpython-team/python3/-/blob/99b2210c …
> Use sitecustomize to emulate venv during python install

- colcon_core/task/python/build.py
- colcon_core/task/python/template/__init__.py
- colcon_core/task/python/template/sitecustomize.py.em
- setup.cfg
- test/spell_check.words
This reverts #512.
Fixes #518.
There is a conditional in `setuptools` that causes some `setup.cfg` options to be ignored while in a virtual environment. While their use is probably incorrect, the anitpattern is too widespread to ignore, and we can't see a way to avoid the conditional in setuptools while still using the `sitecustomize` approach to work around the platform patches.
This will regress colcon builds on Fedora 36, homebrew, and Jammy with `setuptools` installed from pip once again, until we can come up with a new solution.
> Revert "Use sitecustomize to emulate venv during python install"

- colcon_core/event_handler/console_direct.py
- colcon_core/event_handler/console_start_end.py
- test/test_event_handler_console_direct.py
This doesn't cover all of the errors that can occur when `stdout` is closed, but it does improve the situation substantially.
My motivation for this change was a misconfigured invocation in which I was piping `stdout` from colcon to a dead process while `console_direct` was enabled. The console buffer was completely filled up with errors printed to `stderr` about the broken pipe to `stdout`, and I couldn't get far enough back to find the actual root cause of the problem.
When `stdout` or `stderr` are closed, we should stop trying to write to them.
> Improve handling of a broken stdout pipe

- test/test_prefix_path.py
These assertions fail when the AmentPrefixPath extension is loaded and the AMENT_PREFIX_PATH variable is populated. The assertions can be moved into the context manager which is already forcing the unexpected prefix path extensions to be ignored.
Fixes #529
> Fix prefix_path tests when AMENT_PREFIX_PATH is set

- colcon_core/task/python/build.py
- test/spell_check.words
- test/test_build_python.py
When part of a virtual environment, this option is specifically ignored in configuration files by setuptools, but not on the command line.
This is an actual fix for #518, which wasn't actually fixed by #520 but rather made it far less common.
The test added here doesn't actually create a virtual environment to validate the conditions which motivated this fix, but the test will fail if run under a virtual environment without this fix.
> Extract and explicitly pass install-scripts to setuptools

- test/test_shell.py
On Linux, 'echo' is an executable. On Windows, 'echo' is a shell command. Even if we enable the shell while executing this test, the command acts differently on Windows and it is difficult to get it to print newlines as is required by this test.
In any case, we can just use the python executable to print the text instead, which is obviously available during testing.
I'm guessing that this isn't breaking in our windows CI because one of the tools installed in the Windows agents is providing the 'echo' binary on `PATH`. I found this bug while bootstrapping colcon in a minimal Windows environment.
> Stop using 'echo' in shell test

- colcon_core/task/python/build.py
- colcon_core/task/python/template/__init__.py
- colcon_core/task/python/template/sitecustomize.py.em
- setup.cfg
- test/spell_check.words
The problem which necessitated this revert should be resolved independently by #530, meaning we can re-apply this change and take another shot at solving our problems with platform patches to Python paths.
This restores #512
This reverts #520
Closes #519
> Revert "Revert "Use sitecustomize to emulate venv during python install""

- setup.cfg
colcon/ci#11 worked fine for the rest of the colcon repositories, but `colcon-core` also performs a bootstrap test which is having this same problem. Rather than employ another `constraints.txt`, it's easier and more correct to express the constraint in the dependency itself.
...until we come up with a long-term solution, that is.
> Specifically exclude flake8>=6

- test/spell_check.words
- test/test_executor_sequential.py
- test/test_location.py
These two tests modify the global state in a way that makes them runnable only once. This renders colcon's own `--retest-until-fail` feature useless, so this change adds fixtures to restore the state after the test concludes.
> Fix some tests which modify global state

- .github/workflows/ci.yaml
We don't have a particlarly tight coupling to any of these actions, and they're starting to throw deprecation warnings due to deprecations in their internal dependencies.
> Update GitHub Actions major versions

- .github/workflows/ci.yaml
In response to: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Switch to $GITHUB_OUTPUT over deprecated ::set-output

- colcon_core/task/python/test/__init__.py
- colcon_core/task/python/test/pytest.py
- test/test_task_python_test_pytest.py
All of the information and functionality provided by has_test_dependency is already employed by PythonPackageAugmentation when enumerating the dependencies of the package. It's more efficient and flexible, and results in less duplication of information to just read the dependencies from there.
I found no uses of `has_test_dependency` outside of `colcon-core`.
> Deprecate colcon_core.task.python.test.has_test_dependency()

- colcon_core/environment/__init__.py
- colcon_core/shell/__init__.py
- colcon_core/shell/bat.py
- colcon_core/shell/dsv.py
- colcon_core/shell/sh.py
- colcon_core/verb/build.py
- test/test_environment.py
The create_environment_scripts function writes package-specific files to disk based on available shell extensions. This change causes that function, and the functions it calls in ShellExtension instances, to return a list of files which were actually written.
This can be useful in downstream processes to understand what files were installed as part of the package, which could facilitate uninstalling those packages properly.
This change includes a minor version bump to the ShellExtensionPoint. Existing implementations of ShellExtensionPoint will not be broken by this change, but the files they write will not be included in the list until they update to the new extension point API.
Consumers of the ShellExtensionPoint API are all updated within this change.
Implementations to be updated …
> Return list of generated files from create_environment_scripts

- test/test_plugin_system.py
These violations occur in test code which requires suppression of the linter.
> Address some new flake8 violations due to pydocstyle 6.2.0

- colcon_core/argument_parser/action_collector.py
- colcon_core/argument_parser/type_collector.py
- test/test_action_collector.py
- test/test_type_collector.py
This change introduces a new decorator which replaces the `TypeCollectorDecorator`. Enumerating the actions returned by calls to `add_argument` is a cleaner and more efficient way to implement the `SuppressTypeConversions` functionality.
Additionally, this change adds a new suppression class for loosening argument requirements during pre-parsing operations. The `SuppressRequiredActions` class also utilizes the new `ActionCollectorDecorator`.
The motivation for the `SuppressRequiredActions` class (and therefore the `ActionCollectorDecorator`) is that pre-parsing in colcon-defaults and colcon-mixin is causing the error message for missing required arguments to take precedence over the full help text.
For example, invoke the `colcon metadata remove` command without the required positional …
> Add ActionCollectorDecorator, deprecate TypeCollectorDecorator

- colcon_core/task/python/test/__init__.py
- colcon_core/task/python/test/pytest.py
- test/test_task_python_test_pytest.py
It turns out that this mechanism is used to communicate the Python-type dependencies from the setuptools options when processing ament_python packages, which otherwise have ROS-type dependencies. So while we're seeing `python3-pytest` in the test dependency list, the pure python code here looks for the pure python dependency `pytest`.
Since this doesn't actually save us much time and is clearly still needed, I'll take the same approach in the Python project code as was taken in ament_python so that we can all use the same Python testing task.
This reverts #536.
> Revert "Deprecate colcon_core.task.python.test.has_test_dependency()"

- setup.cfg
They must have changed the stacklevel on this warning or something, because this suppression worked at some point. In any case, we need this suppressed to get CI on the multi-part effort to move away from `pkg_resources`.
> Tweak pkg_resources deprecation suppression

- setup.py
The motivation here is to drop the dependency on pkg_resources.
Part of #552
> Simplify version check in setup.py

- test/test_event_reactor.py
These tests essentially queue an event, wait for the event reactor to process the event, and check that an appropriate function was or was not called. The way we were previously waiting for the event reactor thread to do the work left a window between popping the work from the queue and actually passing the event to the observers. If the flush loop finished early in this window, there was a chance that the test's assert would beat the event reactor, which hadn't yet invoked the observers.
Rather than change the behavior of the flush function to also ensure that the popped work had completed processing, we can simply use the queue's integrated work tracking, which won't unblock until there is no work in the queue OR processing.
I believe that this is the cause of the sporadic CI failures …
> Avoid race condition in event_reactor test

- test/test_executor_sequential.py
A few things here:
1. Use a real Job object like the other test. The sequential executor doesn't seem to need it to have a 'identifier' property, but other executors do and we should be consistent.
2. Move stuff out of the try/finally block for the os.kill thread to reduce the likelihood of secondary exceptions.
3. Clear the global job accumulation variable even though we don't check it (which is another conversation entirely).
Motivation behind this change is to port this test to `colcon-parallel-executor`.
> Consistency fixes for test_executor_sequential

- colcon_core/argument_parser/__init__.py
- colcon_core/generic_decorator.py
- test/spell_check.words
- test/test_argument_parser.py
The only current use of the decorator pattern in colcon-core is the argument parser, but the concept can be applied generically in a variety of scenarios.
Motivation for this change is to implement the decorator pattern in the new standards-based Python extensions.
> Extract generic decorator into a reusable class

- colcon_core/subprocess.py
In Python 3.8 and newer, the default event loop on Windows is the ProactorEventLoop, so there's no reason to specifically create one here. We can drop this conditional entirely when we drop Python 3.7 support.
> Use default event loop on Windows in Python 3.8

- colcon_core/executor/sequential.py
In Python versions prior to 3.8, it appears that attempting to close the event loop after a Ctrl-C would reliably hang the process, which would need to be killed.
I've been unable to reproduce the behavior in any newer Python versions, so I think it's time to set the timeline for removing the hack entirely.
This should take care of the common ResourceWarning messages when using newer Python versions.
> Drop Windows event loop hack in Python 3.8+

- colcon_core/argument_type.py
- colcon_core/package_discovery/path.py
- colcon_core/verb/build.py
- colcon_core/verb/test.py
This change enhances the behavior of command line arguments which specify a path which might be relative to the current directory.
The new functionality captures the current working directory when the parser is constructed, and captures a given relative path on the command line by resolving it from that captured working directory. If an argument is left to the default value, it is not resolved by this new functionality and is left for resolution in the consuming code later.
The main use case for this capture-then-resolve behavior is to support changing the working directory of the colcon process. If that happens, the context of where a user intended a relative path to be based is lost, so this change captures the directory early in the colcon startup sequence.
An alternative approach to …
> Resolve path arguments when specified on command line

- colcon_core/package_descriptor.py
- test/test_package_descriptor.py
When enumerating the recursive dependencies for a package descriptor, track which dependency categories the dependency appears to be a part of. This information can be used later to drop certain dependencies or inform a developer of the context around a relationship.
> Track dependency categories on recursive dependencies

- colcon_core/shell/__init__.py
- colcon_core/shell/bat.py
- colcon_core/shell/sh.py
The default value is supposed to be the current prefix only, `COLCON_CURRENT_PREFIX`, and not the concatenated list of all prefixes, `COLCON_PREFIX_PATH`. This fixes a bug(?) introduced in https://github.com/colcon/colcon-core/pull/304. 
As originally commented at https://github.com/colcon/colcon-ros/pull/95#issuecomment-1435102381:
> With the patches
> 
> * [standardize behavior when passing an empty string colcon-core#304](https://github.com/colcon/colcon-core/pull/304) and
> * [standardize behavior when passing an empty string colcon-bash#25](https://github.com/colcon/colcon-bash/pull/25)
> 
> for the various shells the value `''` passed to `create_hook_set_value()` is replaced by `$COLCON_PREFIX_PATH`, so the concatenated list of all colcon workspaces separted with colons. But before …
> Fix the default value for create_hook_set_value()

- colcon_core/package_augmentation/python.py
While I don't think we should discriminate between dependency types for general use, this is useful metadata in some contexts and is easy to include.
> Add 'origin' metadata to python dependencies

- colcon_core/task/__init__.py
This is a follow-up to #411, which made the same change to subprocess.run, which this function calls.
> Allow additional Popen arguments through task.run

- colcon_core/package_augmentation/__init__.py
- colcon_core/package_descriptor.py
- colcon_core/verb/__init__.py
- test/test_argument_default.py
These violations don't show up in our CI right now because we've pinned flake8<6, but when that pin is dropped, we'll have enforcement for this rule.
> Address flake8 E721 violations

- setup.cfg
This suppression is no longer necessary after the fix introduced as part of #573.
> Drop ResourceWarning suppression

- colcon_core/task/python/build.py
It appears that when this varible is set, pytest-cov will import modules during the interpreter initialization before the sitecustomize hook runs. Among the modules imported is sysconfig, which caches its global state before we're able to modify it, thus rendering the entire hook unusable.
The documentation for the 'site' module has more details here, but I wasn't able to find a more aggressive way to prioritize our hook over others. For now, we should suppress COV_CORE_SOURCE to unblock new tests in colcon itself.
> Don't pass COV_CORE_SOURCE to python build subprocess

- colcon_core/task/python/build.py
This function reverts a previous setuptools 'develop' operation, but doesn't actually clean up the artifacts under the build tree that it used to determine that 'develop' was previously used. The result is that after performing a build with --symlink-install, all subsequent builds of that package without --symlink-install will run the commands to "undo" the develop operation even if there is nothing to undo.
This should provide a small performance improvement under those specific circumstances.
> Remove setup.py link after successful _undo_develop

- test/test_build_python.py
A high-level view of this change:
* Take test_build_python and move the majority of the content to _test_build_python
* Make it tolerant of multiple invocations
* Write a new test_build_python that just calls the new method
* Write a _symlink variant
* Write a _symlink_first variant which invokes the function twice
* Write a _symlink_second variant which inverts the order
Requires #579
> Add more tests for task.python.build

- colcon_core/extension_point.py
- test/test_extension_point.py
It appears that the Distribution.name property was introduced in Python 3.10.
It would have been nice if CI would have caught this before I tagged the release.
Fixes #562
> Fix compatibility with Python < 3.10 importlib.metadata

- colcon_core/extension_point.py
- colcon_core/package_identification/python.py
- colcon_core/plugin_system.py
- colcon_core/task/python/test/pytest.py
- debian/patches/setup.cfg.patch
- setup.cfg
- stdeb.cfg
- test/spell_check.words
- test/test_extension_point.py
It appears that we accidentally shipped this incompatible change on Ubuntu Bionic, which is currently under ESM. While we do intend to drop mainline support for Bionic, we should leave it in a good state.
The plan is to release this change in a new version of `colcon-core` and then immediately drop `bionic` from the deb releases, revert this change, and then ship another new version of `colcon-core` which restores the current state.
This reverts #585
This reverts #562
This reverts #560
> Revert from using importlib.metadata back to pkg_resources

- publish-python.yaml
- stdeb.cfg
* Bionic is in ESM and does not package importlib-metadata
* Buster does not package importlib-metadata
* Stretch has Python 3.5 and hasn't been support for a long time now
* Bookworm is the current "stable" Debian
When this change is merged into `colcon-core`, I'm going to make the same change in the other colcon packages without review, since it will effectively be a cherry-pick.
> Update target platforms for debs

- test/test_build_python.py
It appears that newer setuptools versions are no longer normalizing the package name. Rather than update the name that we're looking for, we should just use a normalized name to begin with so that the test works with both old and newer setuptools versions.
> Use a normalized package name in Python build test

- colcon_core/extension_point.py
- test/test_extension_point.py
It seems that the behavior of the `importlib.metadata.entry_points` function changed in Python 3.10 to automatically de-duplicate distributions, but prior to that the "shadowed" distributions were also enumerated. This change specifically ignores "shadowed" distributions so that they aren't identified as extension point overwrites.
Fixes #562
Closes #596
When released, will eventually close ros2/ci#737.
> Fix entry point discovery on Python < 3.10

- setup.cfg
It seems that setuptools has made changes which require us to update our deprecation warning suppression. I think it actually changed twice: once that regressed the stacklevel for the warning, and another time which changed the message entirely.
TIL that suppressing setuptools warnings is akin to whack-a-mole.
In addition to CI, I tested this with setuptools `69.0.3` and `67.7.2`.
> Update setuptools deprecations AGAIN

- colcon_core/executor/__init__.py
- setup.cfg
It seems that flake8 v6 started checking indentation of multi-line string literals, but it doesn't seem to work correctly for f-strings.
Originally pinned in #537.
> Add support for flake8 v6

- colcon_core/task/python/test/__init__.py
- test/spell_check.words
This should help to avoid writing compiled bytecode into the source directories of Python packages during test invocation.
https://docs.python.org/3/using/cmdline.html#envvar-PYTHONDONTWRITEBYTECODE
> Don't write bytecode when invoking Python tests

- test/spell_check.words
- test/test_build_python.py
Switching to a parametrized approach also significantly reduces duplicated code in the test.
> Refactor python build test to improve coverage

- .github/workflows/bootstrap.yaml
- .github/workflows/ci.yaml
This change switches colcon-core to use the new `workflow_call`-based solution for centralized CI definitions. It substantially reduces the boilerplate needed in each repository.
Once this change is merged, I'll make a corresponding change in each colcon extension.
> Switch to workflow_call for GitHub Actions CI

- colcon_core/task/python/build.py
This warning is legitimate and something that developers should be aware of, but at present, the replacement does not provide all of the functionality necessary to support the currently available features in colcon.
When that changes, we'll communicate the upgrade path to users and re-enable the deprecation warning.
Related to #454, #208
> Suppress setup.py deprecation warnings during build

- test/test_extension_point.py
The existing mocks are fragile and don't reliably work in all cases.
This approach uses an actual Distribution instance so that we don't need to modify it to reflect upstream changes to the interface.
> Re-work extension point test mocking

- colcon_core/command.py
- test/test_command.py
It might be useful when measuring performance to invoke colcon with an entire class of extensions blocked. This change "handles" the case where no verbs are available and minimizes the output when there are no verbs or environment variables available.
When invoked normally, this change should not modify any existing behavior.
> Handle invocation with no available verbs or env vars

- colcon_core/extension_point.py
- test/spell_check.words
- test/test_extension_point.py
Whenever we enumerate Python entry points to load colcon extension points, we're re-parsing metadata for every Python package found on the system. Worse yet, accessing attributes on importlib.metadata.Distribution typically results in re-reading the metadata each time, so we're hitting the disk pretty hard.
We don't generally expect the entry points available to change, so we should cache that information once and parse each package's metadata a single time.
Closes #600
> Add an explicit cache on Python entry points

- stdeb.cfg
Upstream Debian has decided to package colcon, and they created a package simply called 'colcon' which provides only the `/usr/bin/colcon` executable and some weak dependencies as a sort of replacement for `colcon-common-extensions`. This conflicts with our `python3-colcon-core` package during unpacking.
We could add `Conflicts: colcon`, but I think this is a great use case for `Replaces:` because the only file provided by `colcon` is `/usr/bin/colcon`, which we obviously provide here. This way, folks can still successfully install `colcon` and get the weak dependencies even if our version of `python3-colcon-core` is installed, and our copy of `/usr/bin/colcon` will take precedence over the one provided by `colcon`.
https://www.debian.org/doc/debian-policy/ch-relationships.html#overwriting …
> Add Debian 'Replaces: colcon' field

- setup.cfg
Rather than suppress A005 completely, we can ignore it in our existing API to prevent new A005 violations from appearing.
I couldn't find a good way to suppress only A005 in the files themselves.
> Suppress flake8 A005 in existing colcon API

- colcon_core/command.py
- test/spell_check.words
The comment in the code has more details, but as of https://github.com/python/cpython/pull/114180 we need to check for both a 3-tuple and a 4-tuple.
> Fix argument parsing in newer Python.

- colcon_core/command.py
I don't see any reason that these statements should be necessary and find their presence confusing.
I'd love to hear feedback either way from any Pythonistas out there who might have some idea why these were added to begin with.
> Drop superfluous 'global' statements from command.py

- colcon_core/executor/sequential.py
- colcon_core/logging.py
- test/test_logging.py
When colcon routes log messages to log files at a different level from the console, it makes it a little more convoluted to determine what log level is actually set.
When we're utilizing non-colcon libraries that also use python's logging module (e.x. ros_buildfarm, rosdistro, etc), we'll typically want to "synchronize" colcon's configured log level with the other library. This function can be used to determine what level colcon's console logging is set to.
> Add colcon_core.logging.get_effective_console_level function

- colcon_core/task/python/build.py
- colcon_core/task/python/colcon_distutils_commands/colcon_distutils_commands-0.0.0.dist-info/METADATA
- colcon_core/task/python/colcon_distutils_commands/colcon_distutils_commands-0.0.0.dist-info/entry_points.txt
- setup.cfg
We don't want anyone taking a dependency on this functionality, and we don't want to interfere with non-colcon use of setuptools or distutils, so it's best to just hide this entry point and make it available only when we're running our builds.
> Make distutils symlink_data command private

- colcon_core/package_decorator.py
- colcon_core/package_descriptor.py
- colcon_core/package_selection/__init__.py
- test/test_package_descriptor.py
When computing the dependency graph, the existing API exposes a parameter for indicating which direct dependency categories to collect as well as what indirect (recursive) dependency categories to collect.
This change allows the caller to specify different recursive dependency categories depending on which category included the dependency in the graph to begin with.
Eventually, this enhancement can be leveraged as part of the "dependency narrowing" effort to drop build-only dependencies from a chain where only runtime dependencies are specified.
> Support complex recursive dependency category specification

- colcon_core/command.py
Rather than show an empty verb block when there are no verbs, just hide the block from the help text entirely.
Before:
```
$ COLCON_EXTENSION_BLOCKLIST=colcon_core.verb colcon --help
usage: colcon [-h] [--log-base LOG_BASE] [--log-level LOG_LEVEL] {} ...
options:
-h, --help            show this help message and exit
--log-base LOG_BASE   The base path for all log directories (default: ./log, to disable: /dev/null)
--log-level LOG_LEVEL
Set log level for the console output, either by numeric or string value (default: warning)
colcon verbs:
{}
Environment variables:
...
```
After:
```
$ COLCON_EXTENSION_BLOCKLIST=colcon_core.verb colcon --help
usage: colcon [-h] [--log-base LOG_BASE] [--log-level LOG_LEVEL]
options:
-h, --help            show this help message and exit
--log-base LOG_BASE …
```
> Hide verb block from help if there are no verbs

- colcon_core/location.py
- test/test_location.py
Explicitly support "no verb" in the logging directory setup, as opposed to treating it as an empty string or raising an exception.
> Add support to logging directory setup for no verb

- colcon_core/command.py
- test/test_command.py
There are no plans to use this feature to allow the 'colcon' executable to be invoked without a verb, but other tools built on colcon-core's framework may not want multiple verbs.
> Add support for command invocation with a 'default verb'

- colcon_core/shell/template/__init__.py
Added some changes to support empy3 and empy4
@cottsay do you mind to update your branch with `master` ?
> Support empy4 and empy3

- test/test_package_identification_python.py
This field was removed from setuptools v72.0.0. We'll continue to read the field in colcon when the underlying setuptools version supports it, but this change drops the testing for its functionality.
Users should already be seeing a deprecation warning from setuptools if they use this field.
> Stop testing 'tests-require' functionality

- test/test_shell_template.py
The 'positive' case was previously completely uncovered on Windows, and there was also no test asserting that the caching mechanism respected differing input variables.
> Add more tests for EmPy template expansion

- colcon_core/shell/template/__init__.py
If the interpreter fails to construct, we don't want to reference it later. Instead, create a separate try/finally block to deal with interpreter shutdown.
This bug is unrelated to the EmPy 4.x transition, but was identified as part of that effort.
> Fix EmPy interpreter shutdown on construction error

- colcon_core/shell/template/__init__.py
The previous approach was to re-implement Interpreter.parse() to iterate over cached tokens where possible. This proved to be a problem when the implementation changed in EmPy 4.x.
The approach implemented here is to create a shim between the Interpreter and Scanner API and record/inject the tokens there, which improves the compatibility by working only at the API boundary and not duplicating chunks of the upstream implementation.
Note that I haven't actually benchmarked either of these caching implementations. They may not be worth the complexity.
> Re-work EmPy token caching

- colcon_core/shell/template/__init__.py
There isn't a clean way to configure EmPy the way we need to which is compatible with both EmPy 3.x and 4.x. Unfortunately, this means that we'll need to have separate code paths.
Additionally, EmPy 4.x doesn't take the `name` argument to Interpreter.string(). From what I can tell, it wasn't used for anything interesting anyway. In particular, exception traces still contain `<string>` instead of the file name.
> Support EmPy 4.x configuration API

- colcon_core/shell/template/__init__.py
This aligns with our strategy for earlier EmPy versions and avoids an assertion deep in EmPy v4 if 'output' is unspecified.
Follow-up to #665
> Use 'output' to configure EmPy v4 redirection

- setup.cfg
> Relax EmPy version requirement now that v4 is working

- colcon_core/python_project/spec.py
- debian/patches/setup.cfg.patch
- setup.cfg
- stdeb.cfg
- test/spell_check.words
- test/test_pyproject_spec.py
This code was originally part of the `colcon-python-project` package. I intend to bring that code into `colcon-core` with proper tests, and hide the functionality behind a feature flag until we're ready to make it the default.
This change specifically adds code to read and cache the `pyproject.toml` spec on package descriptors.
> Add function for reading and caching PEP 518 spec

- colcon_core/python_project/spec.py
- debian/patches/setup.cfg.patch
- setup.cfg
- stdeb.cfg
I'm not thrilled about using the deprecated 'toml' package, but tomli isn't available in Focal as a system package. The changes here will only fall back to 'toml' as a last resort, which should allow us to keep Focal support alive for a while longer.
This should address the deb regression on Focal in colcon-core 0.18.0.
> Support old 'toml' package for Focal

- colcon_core/command.py
Unfortunately, achieving colcon's arbitrary argument parsing involves reaching into argparse private API. There was recently a change to that API which was backported to stable Python releases, and this change is necessary to restore the desired behavior.
> Work around changes to argparse private API

- colcon_core/task/python/build.py
This warning comes up when building ament_python packages with the --symlink-install option.
This is similar to https://github.com/colcon/colcon-core/pull/626, but for symlink installs.
This should "fix" https://github.com/ros2/ros2/issues/1577 .
> Suppress the "easy_install command is deprecated" warning.

- setup.cfg
- test/test_spell_check.py
At this time, scspell is not available for Python 3.13 due to the removal of lib2to3. Until we have another solution, we should skip scspell on Python 3.13 so that we can add that version to the CI matrix as soon as possible.
> Skip scspell tests on Python 3.13+

- test/test_entry_point.py
These tests require pkg_resources, which was removed in Python 3.13.
Note that the `entry_point` API has been deprecated since #562 and is no longer used in any colcon packages maintained here.
> Skip legacy entry_point tests on Python 3.13+

- stdeb.cfg
We continue to see interference between the deb packages we publish from the colcon project and efforts to package colcon as part of mainline Debian and Ubuntu. Using a high Debian-Version value mitigated the problems in most cases, but was not sufficient to eliminate all of the conflicts we're currently experiencing.
Using a debian version suffix which falls late alphabetically appears to give our packages preference by apt. If a user enables a repository which distributes packages created by the colcon project, it is likely that they wish to use these packages instead of the ones packaged by their platform.
Related to colcon/colcon-argcomplete#43 and colcon/colcon.readthedocs.org#103
> Add '+upstream' suffix to published deb version

- colcon_core/executor/__init__.py
- test/test_executor.py
The active executor extension already has a private variable holding the event controller, so it's not difficult to add a method to allow implementations of the executor extensions to publish events as well.
> Allow executor extensions to publish events

- colcon_core/package_discovery/__init__.py
- test/test_package_discovery.py
The current implementation of package discovery follows one of two paths:
1. None of the extensions were specifically enabled via a command line argument, in which case all of the extensions are engaged.
2. Some subset of the extensions were given arguments, in which case the others are ignored and their discover() methods are not called.
This change adds support for discovery extensions which do not expose command line arguments and cannot therefore be specifically enabled, and ensures that those extensions are always engaged.
This is a non-breaking enhancement of the PackageDiscoveryExtensionPoint interface.
> Extend package discovery to support passive mechanisms

- colcon_core/environment/pythonpath.py
- test/spell_check.words
Existing code looks for packages in paths like `.../lib/python3.X/site-packages`, but packages can also be installed to locations like `.../lib64/python3.X/site-packages`. We should look there as well.
> Add Python 'platlib' directory to PYTHONPATH
